### ISSUE TITLE
Create IceCandy token basic

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/icecandy#7]
ERC1155 would be good choice

**Comment by osaguild** [comment]
I'm implementing using ERC721 on #6 . change it later on this issue

**Comment by yu23ki14** [comment]
The reason why I recommend ERC1155 is that, there are two kinds of token, IceCandy and EatenIceCandy

**Comment by osaguild** [comment]
I will implement IceCandy token using ERC721. ERC1155 doesn't match it.
